drop table if exists item;
create table item
(
    id         bigint generated by default as identity,
    item_name  varchar(255),
    price      integer,
    quantity   integer,
    primary key (id)
);